### Start Choreography (Aggregation 5 Orders)
# {
#	"orders":[{
#	   "order_number":"0001",
#	   "item_id":"ABC"
#	},{
#	   "order_number":"0002",
#	   "item_id":"DEF"
#	},{
#	   "order_number":"0003",
#	   "item_id":"ABC"
#	},{
#	   "order_number":"0004",
#	   "item_id":"CAB"
#	},{
#	   "order_number":"0005",
#	   "item_id":"DEF"
#	}]
# }
POST https://lstmp0014.lab.phx.axway.int:32443/executive/webhook HTTP/1.1
Content-Type: application/json
X-Axway-InstanceId: 947615551495837

{
	"eventtype": "execute.choreography",
	"name": "OrderChoreo",
	"payload": "ewoib3JkZXJzIjpbewogICAib3JkZXJfbnVtYmVyIjoiMDAwMSIsCiAgICJpdGVtX2lkIjoiQUJDIgp9LHsKICAgIm9yZGVyX251bWJlciI6IjAwMDIiLAogICAiaXRlbV9pZCI6IkRFRiIKfSx7CiAgICJvcmRlcl9udW1iZXIiOiIwMDAzIiwKICAgIml0ZW1faWQiOiJBQkMiCn0sewogICAib3JkZXJfbnVtYmVyIjoiMDAwNCIsCiAgICJpdGVtX2lkIjoiQ0FCIgp9LHsKICAgIm9yZGVyX251bWJlciI6IjAwMDUiLAogICAiaXRlbV9pZCI6IkRFRiIKfV0KfQ==",
	"metadata": {
		"metadata": "value",
		"choreography": "OrderChoreo"
	}
}
