apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "order-quantity.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "order-quantity.name" . }}
    helm.sh/chart: {{ include "order-quantity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  SERVICE_NAME: {{ .Values.serviceName }}
  SERVICE_VERSION: {{ .Values.serviceVersion | quote}}
  SERVICE_DESCRIPTION: {{ template "order-quantity.description" . }}
  SERVICE_TYPE: {{ .Values.serviceType }}
  LOG_LEVEL: {{ .Values.serviceLogLevel }}